vim.g.mapleader = " "

require("config.lazy")
require("config.colors")
require("config.options")
require("config.keymaps")
require("config.windows")
require("config.navigator")
require("config.lsp")
require("config.completion")
require("config.ui")
require("config.utils")
require("config.treesitter")
require("config.whichkey")
require("config.todo-comments")
require("config.indent-blankline")
require("config.trouble")
require("config.opencode")
require("lazy").setup("plugins")
require("config.markdown")
